### PR TITLE
Update repo2docker to support Singularity

### PR DESCRIPTION
**Pull request by vsoch**
heyo @betatim et al! This is a simple tweak to the default that I think might be ok / appropriate to allow for a repo2docker build to be easily usable with Docker and Singularity containers. For details, see #6. Basically, we need to have the `/home/username` folder be read/writable for all, because when we convert to a Singularity container, without this the notebooks provided by the container will be read only (even with some tweaking and hacks that I figured out to do at runtime to get the python environment working.) To demonstrate the example, here is the walk through of pulling a container with this fix and using with Singularity. Note that I did this on a shared cluster resource (where I don't have docker or sudo).

## Step 1. Pull Docker container to Singularity

```bash
$ echo $SINGULARITY_CACHEDIR
/scratch/users/vsochat/.singularity
[vsochat@sh-ln01 login! /scratch/users/vsochat/share]$ singularity pull docker://vanessa/repo2docker:5a3204ff58
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/vanessa/repo2docker:5a3204ff58
Cache folder set to /scratch/users/vsochat/.singularity/docker
[13/13] |===================================| 100.0% 
Importing: base Singularity environment
Exploding layer: sha256:4ccdce43d1e00fd03ac5438d39e731c16db3dfcf03c68390884b8e8c814221ca.tar.gz
Exploding layer: sha256:c95f13c88d926e6181e0594f76953a14ab80ce002fc6dbc968084a7e18aaafe9.tar.gz
Exploding layer: sha256:82656eee95ad054e0aa75486e7c55b7666c26abbd9bf19373dd349f6e172ce9d.tar.gz
Exploding layer: sha256:78ff727be57a68299558bb40b737669ca5cb9a8db948411d852ec809c14e7a1f.tar.gz
Exploding layer: sha256:448bb314afa553bfb1578121328bbe92d2b5ca0f411967e7a0a200f672ade92f.tar.gz
Exploding layer: sha256:9d5385822d13da4858fc337a2977cb55db7590f4cb898a1c02086e23fee86ce5.tar.gz
Exploding layer: sha256:e8f408ef01287ccbc19922997eed4c744d6b5d1bbc39933f6beda364cc076077.tar.gz
Exploding layer: sha256:63314e962953b7c89dcc6835b4041ecdfc4e9cf954d3d13ce1684897a3ac9da0.tar.gz
Exploding layer: sha256:889bb04638d1859160b996be0b4306a37dc3178958822c7e4185436e47c2ab7b.tar.gz
Exploding layer: sha256:10f98bbddcd0ad2609560add552417678b2aa519cb380766a593371e8070e327.tar.gz
Exploding layer: sha256:de8836d22d768c3e86e65d90a2e00acb288ce50433456c8095c4d13a3e32cf6e.tar.gz
Exploding layer: sha256:30dba8f44db0fd1aa5a251c4158e6ce4ddcdecfbabbb0fdba325de2e8c6ac604.tar.gz
Exploding layer: sha256:e84e3c4959b034a2cd9601a809e34d24556431c8cc86890871efb05192897c85.tar.gz
Exploding layer: sha256:dc6703ca57fbebb41223a39c56878c18dcb851b19000135244c9b6f6323ab39c.tar.gz
Exploding layer: sha256:cd38d573ab49e9a1d7a4eae7db76c92cff9e538bc621114909d2adfc5b952f42.tar.gz
Exploding layer: sha256:0ce49a89ec0ed4446d5ec6f297a734421a2f19cbc1cd8d4a5d26f6990b74501b.tar.gz
Exploding layer: sha256:92679ae5b0edc86eec4266d2306e17f1df3831f1da44a6aefd8c94b63f468f84.tar.gz
Exploding layer: sha256:7edc8299941e6e11f1649b6d6f553b8603070c3d98fd21bdf4f7bd39037e063a.tar.gz
Exploding layer: sha256:1ad5959e8ec8a0b29f9b3c77121d476dea86c1a8d7540136a16ee63bab8b40c5.tar.gz
Exploding layer: sha256:3e9b88f796d006899458aea49d55bbb69e22a24ecb5ea06101b779de2260962c.tar.gz
Exploding layer: sha256:5fd23e9cb6f61c78a7f4a511e89635e8bcd55f57b246f266ca9377692d862ae3.tar.gz
Exploding layer: sha256:e458d018a7cac4f95ed8ee2a3571e1735d872e2e9fa72bd1c51dfd8227144a1a.tar.gz
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
Singularity container built: /scratch/users/vsochat/.singularity/repo2docker-5a3204ff58.simg
Cleaning up...
Done. Container is at: /scratch/users/vsochat/.singularity/repo2docker-5a3204ff58.simg
```
Just for easier use, move to `$PWD`

```bash
mv /scratch/users/vsochat/.singularity/repo2docker-5a3204ff58.simg $PWD
```

## Step 2. Run It

Run as is, setting --pwd in container to be where I know the notebooks are (so I see them in the browser!) Note that I use sdev first to get an interactive node or my group will hate me for running stuff on the login node :p  The one bind I'm doing is to ensure that my local python modules, if I have any in .local, are available in the container.

```bash
sdev
module load singularity

# come up with a random port and hope it's open, lol
PORT=55587

# This is the container I pulled, it's just a file
CONTAINER=repo2docker-5a3204ff58.simg

# Run it!
singularity exec  ${CONTAINER} jupyter notebook --no-browser --port=$PORT --ip 0.0.0.0
```
```bash
[I 08:37:20.998 NotebookApp] Writing notebook server cookie secret to /tmp/jupyter/notebook_cookie_secret
[I 08:37:21.616 NotebookApp] JupyterLab alpha preview extension loaded from /srv/venv/lib/python3.6/site-packages/jupyterlab
[I 08:37:21.616 NotebookApp] JupyterLab application directory is /srv/venv/share/jupyter/lab
[I 08:37:21.625 NotebookApp] nteract extension loaded from /srv/venv/lib/python3.6/site-packages/nteract_on_jupyter
[I 08:37:21.630 NotebookApp] Serving notebooks from local directory: /scratch/users/vsochat/share
[I 08:37:21.630 NotebookApp] 0 active kernels
[I 08:37:21.630 NotebookApp] The Jupyter Notebook is running at:
[I 08:37:21.630 NotebookApp] http://0.0.0.0:55587/?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[I 08:37:21.630 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:37:21.631 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://0.0.0.0:55587/?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

## Step 3. Forward port on localhost
On my local machine, now I want to open the notebook in my browser! Note the node I'm on is  `sh-08-37`

```bash
MACHINE=sh-08-37
PORT=55587
ssh -L $PORT:localhost:$PORT sherlock ssh -L $PORT:localhost:$PORT -N "$MACHINE"
```

### Test 1. New Notebook
Per the running command above (not setting the --pwd, but letting it be the scratch folder where I ran it from) I am able to create a new notebook and import a dependency that is installed in the container (pokemon). The container notebook also save successfully to my scratch!

image

### Test 2. Provided Notebook
But for most data science we would want to provide the notebook that is in the container for use and edit! I control +C'd the command above, and then restarted setting the --pwd of the container to be where the notebook is. If I changed the permission correctly, this should work ok (note that with the current setup it does not, the permissions don't allow write to the folder).

```bash
singularity exec  --pwd /home/username ${CONTAINER} jupyter notebook --no-browser --port=$PORT --ip 0.0.0.0
```
okay this looks good so far - no errors in the console (there would be if we didn't have write permission) and I am now seeing the repository that the container provides as the entrypoint:

image

But can I open, use, and edit the example notebook?

image

yeaaah dawg, I sure can!!

## Summary
In summary, this is a tweak to change the entire permission of  `/home/username` in the Docker container, the base for the repository that the user is building. It's a trivial change for the Docker container because the running user is sudo anyway, but it's a game changer for Singularity because I can:

 1. use the container as a working environment to make new notebooks in my directory of choice (first example)
 2. use the container to work on the notebooks provided in the container, 

But here is a bit of mystery that I don't quite get (and I'm hoping for your help with - it could be a bad singularity bug). With Singularity, I shouldn't be able to write in a read only container. So when write works, it works because the directory is mounted from the host. When I set --pwd it **should** be the case that I'm setting the --pwd of the container to be something that exists in the container and on my host (and in this case it exists in the container but not on the host) and so I would have expected some error with respect to writing files. But I don't see any error, and in fact, I get a message that the example.ipynb is writing... somewhere!

```bash
[I 08:47:11.618 NotebookApp] Writing notebook-signing key to /home/username/.local/share/jupyter/notebook_secret
[W 08:47:11.619 NotebookApp] Notebook example.ipynb is not trusted
[I 08:47:12.058 NotebookApp] Kernel started: 128e9b5b-f035-44fb-b797-feffdd484fd8
[I 08:47:13.449 NotebookApp] Adapting to protocol v5.1 for kernel 128e9b5b-f035-44fb-b797-feffdd484fd8
[I 08:49:12.316 NotebookApp] Saving file at /example.ipynb
[W 08:49:44.315 NotebookApp] Replacing stale connection: 5b430bbd-711c-4d68-bba2-b4a8208c2861:D905C100530846DF986F7B88B83388FA
[I 08:50:20.320 NotebookApp] Saving file at /example.ipynb
[W 08:54:17.310 NotebookApp] Replacing stale connection: 5b430bbd-711c-4d68-bba2-b4a8208c2861:D905C100530846DF986F7B88B83388FA
[I 08:54:21.430 NotebookApp] Saving file at /example.ipynb
[I 08:56:52.580 NotebookApp] Saving file at /example-two.ipynb
[W 08:59:22.291 NotebookApp] Replacing stale connection: 5b430bbd-711c-4d68-bba2-b4a8208c2861:D905C100530846DF986F7B88B83388FA
```
For the life of me, I can't find where on the host the file is writing to... do you have any ideas of where I might look? I looked already at the various jupyter locations in /tmp, etc., but can't find this example-two.ipynb. Does it have something to do with the notebook not being trusted? To verify it's not changing the image file (this should be impossible, actually) I shelled into a different execution of the container binary:

```bash
[vsochat@sh-08-37 /scratch/users/vsochat]$ singularity shell share/repo2docker-5a3204ff58.simg 
Singularity: Invoking an interactive shell within container...

Singularity repo2docker-5a3204ff58.simg:/scratch/users/vsochat> ls /home/username/
example.ipynb  LICENSE	README.md  requirements.txt  venv
```
Is this an issue for making the change here to let Singularity run the container? I don't think so - it's still an improvement on the current because minimally, as a user I can download the notebook from the web interface to my local machine.  

I do, however, want to get some closure about where the notebooks are being saved, just for a sanity check. I'm noticing that I am notified about the credentials saving to `/home/username`

```bash
[I 08:47:11.618 NotebookApp] Writing notebook-signing key to /home/username/.local/share/jupyter/notebook_secret
```
which I **do** have on the host, but I'm not sure if this is from when I've used it there before.

```bash
[vsochat@sh-08-37 /scratch/users/vsochat]$ ls /home/users/vsochat/.local/share/jupyter/
kernels  nbextensions  nbsignatures.db  notebook_secret
```

The other thing that sticks out is that it doesn't trust the notebooks, so maybe they really aren't saved?

```bash
[W 08:47:11.619 NotebookApp] Notebook example.ipynb is not trusted
```

What I'm hoping **isn't** the case is that the notebook is saving somewhere on the host where it should not / somewhere into the container that should be read only, because this would mean I have write in a Singularity image (this should not happen). Let me know if you have other ideas of where to look (on the host) for the files, and I want to ping @dctrud, @cclerget and @godloved to ask about if there are any other Singularity specific locations I might look in.  For the Singularity team - note that this is a running jupyter notebook on a shared cluster resource, forwarded port to my host, and the directory that is serving with `--pwd` has permissions changed (on the Docker Hub build) to `chmod -R 777` It says it's saving and for the life of me I can't find the files! Once we get to the bottom of this, this will be a really awesome feature for (shared resource) cluster users that want quick build and deploy for various interactive working environments. Thanks everyone!

### CODE REVIEW

**Comment by betatim** [comment]
I don't really understand/follow the discussion above :-( Understanding how singularity and repo2docker interact is (I'd say) out of scope for this repository. The repo2docker repo might be a better place for this.

I wouldn't add the `chmod 777` to the generic CI recipe. Instead I'd make a new workflow that includes this step specifically mentioning singularity. This example could also include the step of converting the image to a singularity image?

It seems the fundamental problem is that we don't know the username and UID of the user who wants to run the image. Or the fact that singularity forces you to be you also inside the container. So maybe the real recommendation is that people adjust the template when they copy it to use their username?

**Comment by vsoch** [comment]
Right now we are already saying uid is 1000, so this PR just adds the chmod (which should be trivial for Docker given the user is already root). Does it hurt to add it, really? It seems like more trouble to have another recipe just for the one line, and makes it harder for the huge number of scientific users that want to use Docker and Singularity (possibly the largest jupyter audience?) but maybe that's just me.

**Comment by vsoch** [comment]
Who is username "joyvan?" that name seems to be the hard coded one in the recipe now.

**Comment by vsoch** [comment]
Could you perhaps explain your thinking and logic behind this default? Here is mine:

 1. Scientific containers is the largest use case for notebooks, and specifically, creating reproducible work.
 2. This means a (perhaps even larger) usage of Docker containers *by way of* conversion to Singularity first
 3. A jupyter notebook with incorrect permissions cannot be opened or touched, it's a non starter, never going to work for a Singularity container.

so by making this the default, even though it doesn't significantly change the Docker container, you are enforcing that all future containers created are not going to work with Singularity, which is exactly where they need to work. On the other hand, this simple permissions change ensures that all repo2docker continuous-build containers that are created can be seamlessly used across both.

**Comment by willingc** [comment]
Let's take a moment to pause and reflect on this PR.

First, thanks for the interest and PR @vsoch.

A few thoughts... 
- repo2docker needs to maintain backwards compatibility for the benefit of existing users and projects
- I'm not familiar enough with Singularity to know what the edge cases may be if images are pulled from DockerHub and handled by Singularity
- In general, I'm always cautious when using 777 on a public network.

Perhaps this conversation should move to the repo2docker repo for input by others. I can see how it would be valuable to have Singularity support but I don't have enough information at the moment. Let's expand the discussion to others that have greater depth of experience in the HPC world than I do.

cc/@minrk

**Comment by vsoch** [comment]
@willingc those are definitely things that I agree with - here are some quick thoughts!

## Backwards Compatability
 - If backwards compatibility means some kind of extraction from the container and having the same thing as before, then adding a change to permissions definitely does not support that. 
 - If backwards compatibility means being able to use on environments as old as RHEL 5 / other old school HPC, Docker is a non starter for shared resources in the first place, and the change is essential for *any* kind of compatibility.

## Singularity
Singularity gives the user the same permissions inside and outside the container. Thus, if the user is to have write permission for a notebook, it needs to have that permission set beforehand, as the container itself is read only. As it is currently done with Docker, when you add the files everything is done /owned by root. This is fine as long as you use Docker (and are root). If you try to interact with the files via Singularity, you can't. So TLDR: images pulled from Docker hub, with layers extracted into Singularity containers, will not work. I know this from ample experience, but also testing and using this exact tool, pulling a notebook with this software, and not having it work.

## 777
Me too :) There might be other strategies that would be better? This isn't my strong suite!

I agree that a change would be better actually in repo2docker, but I chose to make it here because the build part has more flexibility in being able to customize the recipe for the container build. I'm definitely open to either / or / something else though! For the record, I'm a software engineer in Research Computing at Stanford, so my primary user base (and working environment) despite loving Docker, is traditional HPC.

**Comment by dtrudg** [comment]
Hello all - coming from the Singularity side of things here I don't think that `chmod 777` is a great idea to add in a default recipe. Even if it makes things work here it's not great to have totally open homes around, as containers like this tend to be reused, and an open home is not expected. It's easy for someone to then do something which is definitely *not* good within an open home dir.

Really to keep things compatible with all singularity workflows and deployments `chmod 777` on a home dir is not enough, and is not a great band-aid. Files ideally need to reside outside of `/home` somewhere, and have sensible appropriate permissions.

There are some notes I wrote about singularity compatibility with docker containers here... https://www.sylabs.io/2018/04/singularity-compatibility-with-docker-containers/ which may be useful reading. 

@vsoch - Seems to me also that repo2docker may be the correct place to have the discussion. It'd have broader scope there too if there were guidelines / workarounds that could apply to all projects using repo2docker.

**Comment by vsoch** [comment]
hey @dctrud ! Yeah it seems too permissive - what would you suggest so that the user can have a working notebook? The idea would need to be that others would share notebooks (so a custom-named home on a per user basis wouldn't do the trick).

For those interested - the workaround I'm using is to have the container "pre-set" with the user's actual home (the `--home` argument in singularity) and then binding the /home/username/.local folder bound to the user's actual $HOME/.local folder:

https://github.com/vsoch/forward/blob/master/sbatches/singularity-jupyter.sbatch#L27

That way, the user still gets a jupyter notebook with the software installed in the container, but the user doesn't get an ability to write to the notebooks provided in the container. The other possibility is that the start script could copy those read only files to a temporary working location, and then the user would be responsible for saving, etc (actually this might be more reasonable, given the mysterious nature of the current strategy that I noted above - I have no idea where the saved files were actually writing to - this is what I wanted to ask you about @dctrud although you seemed to have focused on the permissions bit!) Any ideas about those files?

**Comment by dtrudg** [comment]
@vsoch - I think custom start scripts etc. is going to be far too big an ask for projects where Singularity use is not obviously large. I'd suggest that a good place to begin is to just work with the existing docker containers projects provide, work up a Singularity definition file to build a useful Singularity container (may customize perms / locations / runscripts), and then use that as the basis for interaction / discussion with upstream.

**Comment by vsoch** [comment]
@dctrud I meant a custom start script where I linked from the forward application. :) Very reasonable!

I'm still concerned about not knowing where the files are being written to give in the permissions of 777. Can you comment? This could be a potential security issue across all Singularity containers if a general user can set this permission and then have write access somewhere on the shared resource where they should not.

**Comment by dtrudg** [comment]
@vsoch - I'm not sure what you mean by...

> I'm still concerned about not knowing where the files are being written to give in the permissions of 777. Can you comment? 

I think this is something better brought up on the Singularity slack or issues as this is not related to the binder project here.

**Comment by vsoch** [comment]
@dctrud I documented it in detail above - basically when a folder that is arbitrary in home is created with 777 permissions I am able to use it on a shared resource and write files. The question that is important to figure out is where exactly those files are being written too. I cannot find them in any expected locations either for Singularity mounts, tmp, or for the spaces that I am able to write into. I'm happy to copy paste the issue into a singularity issue if this works better for you.

**Comment by dtrudg** [comment]
@vsoch - if it's writing somewhere in the container that isn't bound into the container from the host then you are writing into the small amount of ephemeral space. It's associated with the container run, and will disappear when the container is stopped.

**Comment by vsoch** [comment]
For example, my concern is that the save is happening to /home/username and I can't see it, which would mean I could write to any arbitrary user home given what I build into the container. We need to verify where the files are being saved to be sure this isn't the case. It's important for something like repo2docker because we need to implement some default that takes this potential usage into account. I appreciate your help with this issue.

**Comment by dtrudg** [comment]
@vsoch - no you can't write to an arbitrary user home dir. The home dir of the specific user running the container is bound in by default, and you can manually bind in things to specific places if you want to... but writing elsewhere in /home would be the ephemeral space. Take a look at `mount` in the container if you are unsure what is coming through from the host. Also `ls /home` you'll not see the home dirs *from the host* of people other than the user that ran the container.

**Comment by vsoch** [comment]
Awesome! Then this should be secure. Could you shed some light on the location of the ephemeral space? I went searching around the temporary directories created by the container as well as the mnt space (where I thought the overlay used to be) and could not find them with grep or find.

**Comment by dtrudg** [comment]
@vsoch - it's a tmpfs (memory based temporary filesystem) and with the way the overlay mounts etc. work you won't find it on the hosts mount namespace. Only visible inside the container.

(this all assumes running singularity where overlayfs is available... things are a bit different when not).

**Comment by vsoch** [comment]
Oh that's super cool! I will instruct users to save elsewhere in this case. @willingc and team - I'm happy to proceed however you think is best. My worry about security is mitigated so now it's an issue of if the builder should create a container that will be usable on HPC or not.

**Pull request closed without merging**
